[package]
name = "cargo-azsphere"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
anyhow = "1"
cargo_toml = "0.11"
toml = "0.5"
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
ctrlc = "3.1.7"
