[package]
name = "cert_store_high_level_app"
version = "0.1.0"
authors = ["Microsoft"]
edition = "2021"

[dependencies]
azure-sphere = { path = "../../../azure-sphere", version = "0.1" }
signal-hook = "0.3.14"
nullable-result = "0.7.0"
hardware = { path = "../../../hardware"}

[package.metadata.azsphere]
extra_files = [
    ["certs/private_key.pem"],
    ["certs/cert.pem"],
    ["certs/root.pem"]
]
