category_id: 30
name: NetConfigError
codes:
  - id: 1
    name: InvalidVersionError
    msg: Invalid version of netconfig error
  - id: 2
    name: UnexpectedJsonValueError
    msg: Unexpected value for json field (wrong type or missing)
  - id: 3
    name: IncompatibleServicesError
    msg: Desired set of network services are incompatible with each other
  - id: 4
    name: StringTooLongError
    msg: String value was too long
  - id: 5
    name: EmptyConfigFileError
    msg: Configuration file was empty
  - id: 6
    name: InvalidMacAddress
    msg: MAC address was invalid
  - id: 7
    name: InvalidIpAddress
    msg: IP address was invalid
  - id: 8
    name: InvalidServiceTypeError
    msg: Service type was invalid
  - id: 9
    name: IPCConnectionFailed
    msg: Network configuration IPC connection failed
  - id: 10
    name: InvalidIPCRequestFormat
    msg: Invalid network configuration request format
  - id: 11
    name: IPCRequestFailed
    msg: Network configuration request failed
  - id: 12
    name: InvalidIPCResponse
    msg: Invalid network configuration response
  - id: 13
    name: IPCRequestNotAllowed
    msg: Network configuration request not allowed
  - id: 14
    name: InvalidInterface
    msg: The provided interface name is not available
  - id: 15
    name: InterfaceNotPermitted
    msg: The operation is not permitted on the specified interface
  - id: 16
    name: TryAgain
    msg: Try the operation again
  - id: 17
    name: InvalidClientId
    msg: Client ID was invalid
  - id: 18
    name: InvalidNetworkInterfaceFile
    msg: Invalid or null network interface file
  - id: 19
    name: InvalidDhcpServerConfig
    msg: Invalid or DHCP Server configuration
  - id: 20
    name: InvalidJsonFormat
    msg: File not valid JSON format
  - id: 21
    name: AccessDenied
    msg: The caller does not have access to the operation
  - id: 22
    name: InvalidSubnetMask
    msg: Subnet mask was invalid
  - id: 23
    name: InvalidGatewayAddress
    msg: Gateway address was invalid
  - id: 24
    name: CouldNotFindInterfaceOption
    msg: The interface configuration could not be found
  - id: 25
    name: OutOfSpace
    msg: Out of space to save configuration
  - id: 26
    name: InvalidFirewallRulesetHook
    msg: Invalid firewall ruleset hook
  - id: 27
    name: InvalidInterfaceAttribute
    msg: Invalid interface attribute
  - id: 28
    name: OutOfRange
    msg: Argument out of range
  - id: 29
    name: BufferTooSmall
    msg: Buffer is too small
  - id: 30
    name: InvalidProxyClientOption
    msg: Invalid proxy client option
  - id: 31
    name: InvalidProxyClientAuthType
    msg: Invalid proxy client authentication mode
  - id: 32
    name: AnonymousAuthDoesNotUseUsernameOrPassword
    msg: Anonymous authentication does not use username or password
  - id: 33
    name: BasicAuthrequiresUsernameAndPassword
    msg: Basic authentication requires username and password
  - id: 34
    name: InvalidUsername
    msg: Invalid username
  - id: 35
    name: InvalidPassword
    msg: Invalid password
  - id: 36
    name: InvalidNoProxyAddresses
    msg: Invalid noProxyAddresses
  - id: 37
    name: InvalidProxyAddress
    msg: Invalid proxy address
  - id: 38
    name: InvalidProxyType
    msg: Invalid proxy type
  - id: 39
    name: ProxyClientConfigurationNotFound
    msg: Proxy client configuration not found
