/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// See TODO(85663) for more information on how to use hardware abstractions
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ..\..\board_config.json.  Do not edit it directly.

#pragma once
#include "ailink_wfm620rsc1.h"

// Application button
#define BOARD_BUTTON_1 AILINK_WFM620RSC1_PIN19_GPIO47

// LED 1 Red channel uses GPIO42.
#define BOARD_LED1_RED AILINK_WFM620RSC1_PIN2_GPIO42

// LED 1 Green channel uses GPIO43.
#define BOARD_LED1_GREEN AILINK_WFM620RSC1_PIN3_GPIO43

// LED 1 Red channel uses GPIO44.
#define BOARD_LED1_BLUE AILINK_WFM620RSC1_PIN4_GPIO44

// LED 2 Red channel uses GPIO45.
#define BOARD_LED2_RED AILINK_WFM620RSC1_PIN17_GPIO45

// LED 2 Green channel uses GPIO46.
#define BOARD_LED2_GREEN AILINK_WFM620RSC1_PIN18_GPIO46

// Uart Enable channel uses GPIO23.
#define BOARD_UART_TX_ENABLE AILINK_WFM620RSC1_PIN23_GPIO23

// AILINK WF-M620-RSC1: WF-M620-RSC1 ISU 1 configured as UART, pin 15 (RX), pin 14 (TX), pin 11 (CTS), pin 10 (RTS).
#define BOARD_UART AILINK_WFM620RSC1_ISU1_UART

// AILINK WF-M620-RSC1: WF-M620-RSC1 ISU 0 configured as I2C,  pin 68 (SDA) and pin 67 (SCL).
#define BOARD_I2C AILINK_WFM620RSC1_ISU3_I2C

// AILINK WF-M620-RSC1: WF-M620-RSC1 ISU 0 configured as SPI, pin 7 (MISO), pin 5 (SCLK), pin 8 (CSA), pin 6 (MOSI) and pin 9 (CSB)
#define BOARD_SPI AILINK_WFM620RSC1_ISU0_SPI

// MT3620 SPI Chip Select (CS) value "A". This is not a peripheral identifier, and so has no meaning in an app manifest.
#define BOARD_SPI_CS MT3620_SPI_CS_A

