name: ci

on:
    push:
        branches: [main, chwhitwo/github-actions]
    pull_request:
        branches: [main, chwhitwo/github-actions]

jobs:
    sanity-check:
        name: sanity-check
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Install latest Azure Sphere SDK
              shell: bash
              run: |
                curl -L https://aka.ms/AzureSphereSDKInstall/Linux | tar zxf -
                chmod +x install_azure_sphere_sdk.sh
                sudo ./install_azure_sphere_sdk.sh -y

            - name: Sanity check all the projects
              shell: bash
              run: |
                ./scripts/build-all.sh